# Site settings
title: Illuminator Brothers
email: contact@illuminatorbros.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://illuminatorbros.com" # the base hostname & protocol for your site

facebook_username: illuminatorbros
instagram_username: illuminatorbros

# Build settings
markdown: kramdown
